# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    env: 
      VAR: "YVARS"
      HTTP_PROXY: "http://my.proxy:8080"
      HTTPS_PROXY: "http://my.proxy:8080"
    steps:
      - run: env
      - run: echo $HTTPS_PROXY
      - name: Install Poetry
        uses: snok/install-poetry@v1
